image: node:lts-alpine

stages:
    - setup
    - test

setup:
    stage: setup
    script:
        - yarn install
    cache:
        key:
            files:
                - yarn.lock
        paths:
            - node_modules

test:
    stage: test
    script:
        - yarn test
    cache:
        key:
            files:
                - yarn.lock
        paths:
            - node_modules
        policy: pull

coverage:
    stage: test
    script:
        - yarn test:coverage
    artifacts:
        when: always
        paths:
            - reports/coverage
        expire_in: 30 days
    cache:
        key:
            files:
                - yarn.lock
        paths:
            - node_modules
        policy: pull

mutation:
    stage: test
    script:
        - yarn test:mutation
    artifacts:
        when: always
        paths:
            - reports/mutation
        expire_in: 30 days
    cache:
        key:
            files:
                - yarn.lock
        paths:
            - node_modules
        policy: pull
